[env:m5stack-cardputer]
platform = espressif32
board = m5stack-cores3
framework = arduino
monitor_speed = 115200
upload_speed = 1500000
lib_deps = 
    m5stack/M5Cardputer@^1.0.1
    z3t0/IRremote@^4.3.0
